// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "exp_generic_decimal16_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic exp_generic_decimal16_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic exp_generic_decimal16_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> exp_generic_decimal16_s::ap_ST_fsm_pp0_stage0 = "1";
const bool exp_generic_decimal16_s::ap_const_boolean_1 = true;
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool exp_generic_decimal16_s::ap_const_boolean_0 = false;
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_F = "1111";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_A = "1010";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_E = "1110";
const sc_lv<5> exp_generic_decimal16_s::ap_const_lv5_1F = "11111";
const sc_lv<10> exp_generic_decimal16_s::ap_const_lv10_0 = "0000000000";
const sc_lv<6> exp_generic_decimal16_s::ap_const_lv6_31 = "110001";
const sc_lv<2> exp_generic_decimal16_s::ap_const_lv2_1 = "1";
const sc_lv<12> exp_generic_decimal16_s::ap_const_lv12_0 = "000000000000";
const sc_lv<3> exp_generic_decimal16_s::ap_const_lv3_0 = "000";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_5 = "101";
const sc_lv<5> exp_generic_decimal16_s::ap_const_lv5_F = "1111";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_3 = "11";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_12 = "10010";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_9 = "1001";
const sc_lv<6> exp_generic_decimal16_s::ap_const_lv6_0 = "000000";
const sc_lv<12> exp_generic_decimal16_s::ap_const_lv12_800 = "100000000000";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_C = "1100";
const sc_lv<7> exp_generic_decimal16_s::ap_const_lv7_1 = "1";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_7 = "111";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_19 = "11001";
const sc_lv<1> exp_generic_decimal16_s::ap_const_lv1_0 = "0";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_4 = "100";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_D = "1101";
const sc_lv<15> exp_generic_decimal16_s::ap_const_lv15_4 = "100";
const sc_lv<4> exp_generic_decimal16_s::ap_const_lv4_0 = "0000";
const sc_lv<1> exp_generic_decimal16_s::ap_const_lv1_1 = "1";
const sc_lv<16> exp_generic_decimal16_s::ap_const_lv16_7FFF = "111111111111111";
const sc_lv<16> exp_generic_decimal16_s::ap_const_lv16_7C00 = "111110000000000";
const sc_lv<16> exp_generic_decimal16_s::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_11 = "10001";
const sc_lv<7> exp_generic_decimal16_s::ap_const_lv7_7F = "1111111";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_6 = "110";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_B = "1011";
const sc_lv<7> exp_generic_decimal16_s::ap_const_lv7_72 = "1110010";
const sc_lv<32> exp_generic_decimal16_s::ap_const_lv32_10 = "10000";
const sc_lv<19> exp_generic_decimal16_s::ap_const_lv19_171 = "101110001";
const sc_lv<26> exp_generic_decimal16_s::ap_const_lv26_58B90 = "1011000101110010000";

exp_generic_decimal16_s::exp_generic_decimal16_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_U = new exp_generic_decimal16_s_table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0bkb("table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_U");
    table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_U->clk(ap_clk);
    table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_U->reset(ap_rst);
    table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_U->address0(table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0);
    table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_U->ce0(table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0);
    table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_U->q0(table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0);
    calcPerceptron_mac_muladd_10ns_10s_13s_19_4_1_U1 = new calcPerceptron_mac_muladd_10ns_10s_13s_19_4_1<1,4,10,10,13,19>("calcPerceptron_mac_muladd_10ns_10s_13s_19_4_1_U1");
    calcPerceptron_mac_muladd_10ns_10s_13s_19_4_1_U1->clk(ap_clk);
    calcPerceptron_mac_muladd_10ns_10s_13s_19_4_1_U1->reset(ap_rst);
    calcPerceptron_mac_muladd_10ns_10s_13s_19_4_1_U1->din0(grp_fu_777_p0);
    calcPerceptron_mac_muladd_10ns_10s_13s_19_4_1_U1->din1(m_fix_hi_V_fu_321_p4);
    calcPerceptron_mac_muladd_10ns_10s_13s_19_4_1_U1->din2(rhs_V_fu_389_p3);
    calcPerceptron_mac_muladd_10ns_10s_13s_19_4_1_U1->ce(ap_var_for_const0);
    calcPerceptron_mac_muladd_10ns_10s_13s_19_4_1_U1->dout(grp_fu_777_p3);
    calcPerceptron_mul_mul_20ns_7s_26_4_1_U2 = new calcPerceptron_mul_mul_20ns_7s_26_4_1<1,4,20,7,26>("calcPerceptron_mul_mul_20ns_7s_26_4_1_U2");
    calcPerceptron_mul_mul_20ns_7s_26_4_1_U2->clk(ap_clk);
    calcPerceptron_mul_mul_20ns_7s_26_4_1_U2->reset(ap_rst);
    calcPerceptron_mul_mul_20ns_7s_26_4_1_U2->din0(grp_fu_788_p0);
    calcPerceptron_mul_mul_20ns_7s_26_4_1_U2->din1(r_exp_V_3_fu_439_p3);
    calcPerceptron_mul_mul_20ns_7s_26_4_1_U2->ce(ap_var_for_const0);
    calcPerceptron_mul_mul_20ns_7s_26_4_1_U2->dout(grp_fu_788_p2);
    calcPerceptron_mac_muladd_4ns_5ns_19ns_19_4_1_U3 = new calcPerceptron_mac_muladd_4ns_5ns_19ns_19_4_1<1,4,4,5,19,19>("calcPerceptron_mac_muladd_4ns_5ns_19ns_19_4_1_U3");
    calcPerceptron_mac_muladd_4ns_5ns_19ns_19_4_1_U3->clk(ap_clk);
    calcPerceptron_mac_muladd_4ns_5ns_19ns_19_4_1_U3->reset(ap_rst);
    calcPerceptron_mac_muladd_4ns_5ns_19ns_19_4_1_U3->din0(grp_fu_795_p0);
    calcPerceptron_mac_muladd_4ns_5ns_19ns_19_4_1_U3->din1(grp_fu_795_p1);
    calcPerceptron_mac_muladd_4ns_5ns_19ns_19_4_1_U3->din2(grp_fu_795_p2);
    calcPerceptron_mac_muladd_4ns_5ns_19ns_19_4_1_U3->ce(ap_var_for_const0);
    calcPerceptron_mac_muladd_4ns_5ns_19ns_19_4_1_U3->dout(grp_fu_795_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln805_fu_425_p2);
    sensitive << ( tmp_1_fu_400_p4 );

    SC_METHOD(thread_and_ln18_fu_199_p2);
    sensitive << ( icmp_ln833_fu_175_p2 );
    sensitive << ( icmp_ln833_1_fu_193_p2 );

    SC_METHOD(thread_and_ln209_fu_187_p2);
    sensitive << ( icmp_ln833_fu_175_p2 );
    sensitive << ( icmp_ln837_fu_181_p2 );

    SC_METHOD(thread_and_ln338_1_fu_735_p2);
    sensitive << ( icmp_ln338_reg_870_pp0_iter9_reg );
    sensitive << ( xor_ln338_1_fu_729_p2 );

    SC_METHOD(thread_and_ln338_fu_685_p2);
    sensitive << ( icmp_ln338_reg_870_pp0_iter9_reg );
    sensitive << ( or_ln338_fu_603_p2 );

    SC_METHOD(thread_and_ln849_fu_695_p2);
    sensitive << ( icmp_ln849_fu_597_p2 );
    sensitive << ( xor_ln338_fu_690_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter7);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter8);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_ap_idle_pp0_0to9);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to9 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( sel_tmp16_fu_763_p2 );
    sensitive << ( select_ln214_2_fu_721_p3 );

    SC_METHOD(thread_ashr_ln1287_1_fu_363_p2);
    sensitive << ( m_fix_l_V_reg_854 );
    sensitive << ( sext_ln1311_1_fu_349_p1 );

    SC_METHOD(thread_ashr_ln1287_fu_283_p2);
    sensitive << ( m_frac_l_V_fu_237_p3 );
    sensitive << ( sext_ln1311_3_fu_275_p1 );

    SC_METHOD(thread_bitcast_ln667_fu_675_p1);
    sensitive << ( p_Result_14_fu_665_p4 );

    SC_METHOD(thread_e_frac_V_fu_223_p2);
    sensitive << ( p_Result_s_fu_215_p3 );

    SC_METHOD(thread_exp_Z1_hi_V_fu_500_p4);
    sensitive << ( table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0 );

    SC_METHOD(thread_grp_fu_777_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_788_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_grp_fu_795_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( grp_fu_795_p00 );

    SC_METHOD(thread_grp_fu_795_p00);
    sensitive << ( m_diff_lo_V_reg_899 );

    SC_METHOD(thread_grp_fu_795_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( grp_fu_795_p10 );

    SC_METHOD(thread_grp_fu_795_p10);
    sensitive << ( exp_Z1_hi_V_fu_500_p4 );

    SC_METHOD(thread_grp_fu_795_p2);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ret_V_4_fu_520_p2 );

    SC_METHOD(thread_icmp_ln338_1_fu_383_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( shl_ln_fu_375_p3 );
    sensitive << ( sext_ln1285_fu_352_p1 );

    SC_METHOD(thread_icmp_ln338_fu_343_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( m_exp_fu_209_p2 );

    SC_METHOD(thread_icmp_ln805_fu_419_p2);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( trunc_ln805_fu_416_p1 );

    SC_METHOD(thread_icmp_ln833_1_fu_193_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_V_1_fu_171_p1 );

    SC_METHOD(thread_icmp_ln833_fu_175_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_V_fu_161_p4 );

    SC_METHOD(thread_icmp_ln837_fu_181_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_V_1_fu_171_p1 );

    SC_METHOD(thread_icmp_ln849_fu_597_p2);
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_10_fu_587_p4 );

    SC_METHOD(thread_icmp_ln853_fu_623_p2);
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( r_exp_V_2_fu_580_p3 );

    SC_METHOD(thread_isNeg_fu_245_p3);
    sensitive << ( m_exp_fu_209_p2 );

    SC_METHOD(thread_lhs_V_1_fu_517_p1);
    sensitive << ( exp_Z1_V_reg_909_pp0_iter8_reg );

    SC_METHOD(thread_lhs_V_fu_451_p1);
    sensitive << ( r_V_6_reg_849_pp0_iter5_reg );

    SC_METHOD(thread_m_diff_hi_V_fu_481_p4);
    sensitive << ( ret_V_3_fu_475_p2 );

    SC_METHOD(thread_m_diff_lo_V_fu_491_p1);
    sensitive << ( ret_V_3_fu_475_p2 );

    SC_METHOD(thread_m_exp_2_fu_263_p3);
    sensitive << ( isNeg_fu_245_p3 );
    sensitive << ( m_exp_fu_209_p2 );
    sensitive << ( sext_ln1311_fu_259_p1 );

    SC_METHOD(thread_m_exp_fu_209_p2);
    sensitive << ( zext_ln659_fu_205_p1 );

    SC_METHOD(thread_m_fix_hi_V_fu_321_p4);
    sensitive << ( r_V_6_fu_303_p3 );

    SC_METHOD(thread_m_frac_l_V_fu_237_p3);
    sensitive << ( select_ln253_fu_229_p3 );

    SC_METHOD(thread_or_ln214_1_fu_556_p2);
    sensitive << ( and_ln209_reg_811_pp0_iter9_reg );
    sensitive << ( and_ln18_reg_818_pp0_iter9_reg );

    SC_METHOD(thread_or_ln214_fu_544_p2);
    sensitive << ( and_ln209_reg_811_pp0_iter9_reg );
    sensitive << ( x_is_pinf_fu_539_p2 );

    SC_METHOD(thread_or_ln338_fu_603_p2);
    sensitive << ( icmp_ln338_1_reg_878_pp0_iter9_reg );
    sensitive << ( icmp_ln849_fu_597_p2 );

    SC_METHOD(thread_or_ln849_1_fu_740_p2);
    sensitive << ( icmp_ln338_reg_870_pp0_iter9_reg );
    sensitive << ( icmp_ln849_fu_597_p2 );

    SC_METHOD(thread_or_ln849_2_fu_751_p2);
    sensitive << ( and_ln338_1_fu_735_p2 );
    sensitive << ( xor_ln849_fu_745_p2 );

    SC_METHOD(thread_or_ln849_fu_701_p2);
    sensitive << ( and_ln338_fu_685_p2 );
    sensitive << ( and_ln849_fu_695_p2 );

    SC_METHOD(thread_out_exp_V_fu_659_p2);
    sensitive << ( trunc_ln168_fu_655_p1 );

    SC_METHOD(thread_p_Result_12_fu_153_p3);
    sensitive << ( p_Val2_s_fu_149_p1 );

    SC_METHOD(thread_p_Result_14_fu_665_p4);
    sensitive << ( out_exp_V_fu_659_p2 );
    sensitive << ( tmp_V_2_fu_647_p3 );

    SC_METHOD(thread_p_Result_7_fu_409_p3);
    sensitive << ( grp_fu_777_p3 );

    SC_METHOD(thread_p_Result_s_fu_215_p3);
    sensitive << ( tmp_V_1_fu_171_p1 );

    SC_METHOD(thread_p_Val2_s_fu_149_p1);
    sensitive << ( x );

    SC_METHOD(thread_r_V_6_fu_303_p3);
    sensitive << ( isNeg_fu_245_p3 );
    sensitive << ( sext_ln1287_1_fu_289_p1 );
    sensitive << ( trunc_ln1310_fu_299_p1 );

    SC_METHOD(thread_r_exp_V_2_fu_580_p3);
    sensitive << ( r_exp_V_3_reg_888_pp0_iter9_reg );
    sensitive << ( tmp_9_fu_568_p3 );
    sensitive << ( r_exp_V_fu_575_p2 );

    SC_METHOD(thread_r_exp_V_3_fu_439_p3);
    sensitive << ( tmp_1_fu_400_p4 );
    sensitive << ( p_Result_7_fu_409_p3 );
    sensitive << ( select_ln805_fu_431_p3 );

    SC_METHOD(thread_r_exp_V_fu_575_p2);
    sensitive << ( r_exp_V_3_reg_888_pp0_iter9_reg );

    SC_METHOD(thread_ret_V_3_fu_475_p2);
    sensitive << ( lhs_V_fu_451_p1 );
    sensitive << ( sext_ln682_1_fu_471_p1 );

    SC_METHOD(thread_ret_V_4_fu_520_p2);
    sensitive << ( lhs_V_1_fu_517_p1 );

    SC_METHOD(thread_rhs_V_1_fu_463_p3);
    sensitive << ( tmp_4_fu_454_p4 );

    SC_METHOD(thread_rhs_V_fu_389_p3);
    sensitive << ( p_Result_13_reg_860_pp0_iter1_reg );

    SC_METHOD(thread_sel_tmp16_fu_763_p2);
    sensitive << ( tmp_fu_757_p2 );
    sensitive << ( icmp_ln853_fu_623_p2 );

    SC_METHOD(thread_sel_tmp5_fu_707_p2);
    sensitive << ( or_ln849_fu_701_p2 );
    sensitive << ( xor_ln214_fu_679_p2 );

    SC_METHOD(thread_sel_tmp6_fu_713_p3);
    sensitive << ( sel_tmp5_fu_707_p2 );
    sensitive << ( select_ln339_fu_615_p3 );
    sensitive << ( bitcast_ln667_fu_675_p1 );

    SC_METHOD(thread_select_ln1322_fu_368_p3);
    sensitive << ( isNeg_reg_834 );
    sensitive << ( shl_ln1253_1_fu_358_p2 );
    sensitive << ( ashr_ln1287_1_fu_363_p2 );

    SC_METHOD(thread_select_ln214_1_fu_560_p3);
    sensitive << ( or_ln214_fu_544_p2 );
    sensitive << ( select_ln214_fu_549_p3 );

    SC_METHOD(thread_select_ln214_2_fu_721_p3);
    sensitive << ( or_ln214_1_fu_556_p2 );
    sensitive << ( select_ln214_1_fu_560_p3 );
    sensitive << ( sel_tmp6_fu_713_p3 );

    SC_METHOD(thread_select_ln214_fu_549_p3);
    sensitive << ( and_ln209_reg_811_pp0_iter9_reg );

    SC_METHOD(thread_select_ln253_fu_229_p3);
    sensitive << ( p_Result_12_fu_153_p3 );
    sensitive << ( p_Result_s_fu_215_p3 );
    sensitive << ( e_frac_V_fu_223_p2 );

    SC_METHOD(thread_select_ln339_fu_615_p3);
    sensitive << ( tmp_11_fu_608_p3 );

    SC_METHOD(thread_select_ln805_fu_431_p3);
    sensitive << ( tmp_1_fu_400_p4 );
    sensitive << ( icmp_ln805_fu_419_p2 );
    sensitive << ( add_ln805_fu_425_p2 );

    SC_METHOD(thread_sext_ln1285_fu_352_p1);
    sensitive << ( m_frac_l_V_reg_829 );

    SC_METHOD(thread_sext_ln1287_1_fu_289_p1);
    sensitive << ( ashr_ln1287_fu_283_p2 );

    SC_METHOD(thread_sext_ln1287_fu_279_p1);
    sensitive << ( m_frac_l_V_fu_237_p3 );

    SC_METHOD(thread_sext_ln1311_1_fu_349_p1);
    sensitive << ( m_exp_2_reg_839 );

    SC_METHOD(thread_sext_ln1311_2_fu_271_p1);
    sensitive << ( m_exp_2_fu_263_p3 );

    SC_METHOD(thread_sext_ln1311_2cast_fu_355_p1);
    sensitive << ( sext_ln1311_2_reg_844 );

    SC_METHOD(thread_sext_ln1311_3_fu_275_p1);
    sensitive << ( m_exp_2_fu_263_p3 );

    SC_METHOD(thread_sext_ln1311_fu_259_p1);
    sensitive << ( sub_ln1311_fu_253_p2 );

    SC_METHOD(thread_sext_ln682_1_fu_471_p1);
    sensitive << ( rhs_V_1_fu_463_p3 );

    SC_METHOD(thread_shl_ln1253_1_fu_358_p2);
    sensitive << ( m_fix_l_V_reg_854 );
    sensitive << ( sext_ln1311_2cast_fu_355_p1 );

    SC_METHOD(thread_shl_ln1253_fu_293_p2);
    sensitive << ( sext_ln1311_2_fu_271_p1 );
    sensitive << ( sext_ln1287_fu_279_p1 );

    SC_METHOD(thread_shl_ln_fu_375_p3);
    sensitive << ( select_ln1322_fu_368_p3 );

    SC_METHOD(thread_sub_ln1311_fu_253_p2);
    sensitive << ( tmp_V_fu_161_p4 );

    SC_METHOD(thread_table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( zext_ln498_fu_495_p1 );

    SC_METHOD(thread_table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0);
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_tmp_10_fu_587_p4);
    sensitive << ( r_exp_V_2_fu_580_p3 );

    SC_METHOD(thread_tmp_11_fu_608_p3);
    sensitive << ( select_ln253_reg_824_pp0_iter9_reg );

    SC_METHOD(thread_tmp_1_fu_400_p4);
    sensitive << ( grp_fu_777_p3 );

    SC_METHOD(thread_tmp_2_fu_629_p4);
    sensitive << ( grp_fu_795_p3 );

    SC_METHOD(thread_tmp_3_fu_638_p4);
    sensitive << ( grp_fu_795_p3 );

    SC_METHOD(thread_tmp_4_fu_454_p4);
    sensitive << ( grp_fu_788_p2 );

    SC_METHOD(thread_tmp_9_fu_568_p3);
    sensitive << ( grp_fu_795_p3 );

    SC_METHOD(thread_tmp_V_1_fu_171_p1);
    sensitive << ( p_Val2_s_fu_149_p1 );

    SC_METHOD(thread_tmp_V_2_fu_647_p3);
    sensitive << ( tmp_9_fu_568_p3 );
    sensitive << ( tmp_3_fu_638_p4 );
    sensitive << ( tmp_2_fu_629_p4 );

    SC_METHOD(thread_tmp_V_fu_161_p4);
    sensitive << ( p_Val2_s_fu_149_p1 );

    SC_METHOD(thread_tmp_fu_757_p2);
    sensitive << ( xor_ln214_fu_679_p2 );
    sensitive << ( or_ln849_2_fu_751_p2 );

    SC_METHOD(thread_trunc_ln1310_fu_299_p1);
    sensitive << ( shl_ln1253_fu_293_p2 );

    SC_METHOD(thread_trunc_ln168_fu_655_p1);
    sensitive << ( r_exp_V_2_fu_580_p3 );

    SC_METHOD(thread_trunc_ln805_fu_416_p1);
    sensitive << ( grp_fu_777_p3 );

    SC_METHOD(thread_x_is_pinf_fu_539_p2);
    sensitive << ( and_ln18_reg_818_pp0_iter9_reg );
    sensitive << ( xor_ln936_fu_534_p2 );

    SC_METHOD(thread_xor_ln214_fu_679_p2);
    sensitive << ( or_ln214_1_fu_556_p2 );

    SC_METHOD(thread_xor_ln338_1_fu_729_p2);
    sensitive << ( or_ln338_fu_603_p2 );

    SC_METHOD(thread_xor_ln338_fu_690_p2);
    sensitive << ( icmp_ln338_reg_870_pp0_iter9_reg );

    SC_METHOD(thread_xor_ln849_fu_745_p2);
    sensitive << ( or_ln849_1_fu_740_p2 );

    SC_METHOD(thread_xor_ln936_fu_534_p2);
    sensitive << ( p_Result_12_reg_806_pp0_iter9_reg );

    SC_METHOD(thread_zext_ln498_fu_495_p1);
    sensitive << ( m_diff_hi_V_fu_481_p4 );

    SC_METHOD(thread_zext_ln659_fu_205_p1);
    sensitive << ( tmp_V_fu_161_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "exp_generic_decimal16_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x, "(port)x");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4, "ap_block_state5_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter5, "ap_block_state6_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter6, "ap_block_state7_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter7, "ap_block_state8_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter8, "ap_block_state9_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter9, "ap_block_state10_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter10, "ap_block_state11_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0, "table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0");
    sc_trace(mVcdFile, table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0, "table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0");
    sc_trace(mVcdFile, table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0, "table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0");
    sc_trace(mVcdFile, p_Result_12_fu_153_p3, "p_Result_12_fu_153_p3");
    sc_trace(mVcdFile, p_Result_12_reg_806, "p_Result_12_reg_806");
    sc_trace(mVcdFile, p_Result_12_reg_806_pp0_iter1_reg, "p_Result_12_reg_806_pp0_iter1_reg");
    sc_trace(mVcdFile, p_Result_12_reg_806_pp0_iter2_reg, "p_Result_12_reg_806_pp0_iter2_reg");
    sc_trace(mVcdFile, p_Result_12_reg_806_pp0_iter3_reg, "p_Result_12_reg_806_pp0_iter3_reg");
    sc_trace(mVcdFile, p_Result_12_reg_806_pp0_iter4_reg, "p_Result_12_reg_806_pp0_iter4_reg");
    sc_trace(mVcdFile, p_Result_12_reg_806_pp0_iter5_reg, "p_Result_12_reg_806_pp0_iter5_reg");
    sc_trace(mVcdFile, p_Result_12_reg_806_pp0_iter6_reg, "p_Result_12_reg_806_pp0_iter6_reg");
    sc_trace(mVcdFile, p_Result_12_reg_806_pp0_iter7_reg, "p_Result_12_reg_806_pp0_iter7_reg");
    sc_trace(mVcdFile, p_Result_12_reg_806_pp0_iter8_reg, "p_Result_12_reg_806_pp0_iter8_reg");
    sc_trace(mVcdFile, p_Result_12_reg_806_pp0_iter9_reg, "p_Result_12_reg_806_pp0_iter9_reg");
    sc_trace(mVcdFile, and_ln209_fu_187_p2, "and_ln209_fu_187_p2");
    sc_trace(mVcdFile, and_ln209_reg_811, "and_ln209_reg_811");
    sc_trace(mVcdFile, and_ln209_reg_811_pp0_iter1_reg, "and_ln209_reg_811_pp0_iter1_reg");
    sc_trace(mVcdFile, and_ln209_reg_811_pp0_iter2_reg, "and_ln209_reg_811_pp0_iter2_reg");
    sc_trace(mVcdFile, and_ln209_reg_811_pp0_iter3_reg, "and_ln209_reg_811_pp0_iter3_reg");
    sc_trace(mVcdFile, and_ln209_reg_811_pp0_iter4_reg, "and_ln209_reg_811_pp0_iter4_reg");
    sc_trace(mVcdFile, and_ln209_reg_811_pp0_iter5_reg, "and_ln209_reg_811_pp0_iter5_reg");
    sc_trace(mVcdFile, and_ln209_reg_811_pp0_iter6_reg, "and_ln209_reg_811_pp0_iter6_reg");
    sc_trace(mVcdFile, and_ln209_reg_811_pp0_iter7_reg, "and_ln209_reg_811_pp0_iter7_reg");
    sc_trace(mVcdFile, and_ln209_reg_811_pp0_iter8_reg, "and_ln209_reg_811_pp0_iter8_reg");
    sc_trace(mVcdFile, and_ln209_reg_811_pp0_iter9_reg, "and_ln209_reg_811_pp0_iter9_reg");
    sc_trace(mVcdFile, and_ln18_fu_199_p2, "and_ln18_fu_199_p2");
    sc_trace(mVcdFile, and_ln18_reg_818, "and_ln18_reg_818");
    sc_trace(mVcdFile, and_ln18_reg_818_pp0_iter1_reg, "and_ln18_reg_818_pp0_iter1_reg");
    sc_trace(mVcdFile, and_ln18_reg_818_pp0_iter2_reg, "and_ln18_reg_818_pp0_iter2_reg");
    sc_trace(mVcdFile, and_ln18_reg_818_pp0_iter3_reg, "and_ln18_reg_818_pp0_iter3_reg");
    sc_trace(mVcdFile, and_ln18_reg_818_pp0_iter4_reg, "and_ln18_reg_818_pp0_iter4_reg");
    sc_trace(mVcdFile, and_ln18_reg_818_pp0_iter5_reg, "and_ln18_reg_818_pp0_iter5_reg");
    sc_trace(mVcdFile, and_ln18_reg_818_pp0_iter6_reg, "and_ln18_reg_818_pp0_iter6_reg");
    sc_trace(mVcdFile, and_ln18_reg_818_pp0_iter7_reg, "and_ln18_reg_818_pp0_iter7_reg");
    sc_trace(mVcdFile, and_ln18_reg_818_pp0_iter8_reg, "and_ln18_reg_818_pp0_iter8_reg");
    sc_trace(mVcdFile, and_ln18_reg_818_pp0_iter9_reg, "and_ln18_reg_818_pp0_iter9_reg");
    sc_trace(mVcdFile, select_ln253_fu_229_p3, "select_ln253_fu_229_p3");
    sc_trace(mVcdFile, select_ln253_reg_824, "select_ln253_reg_824");
    sc_trace(mVcdFile, select_ln253_reg_824_pp0_iter1_reg, "select_ln253_reg_824_pp0_iter1_reg");
    sc_trace(mVcdFile, select_ln253_reg_824_pp0_iter2_reg, "select_ln253_reg_824_pp0_iter2_reg");
    sc_trace(mVcdFile, select_ln253_reg_824_pp0_iter3_reg, "select_ln253_reg_824_pp0_iter3_reg");
    sc_trace(mVcdFile, select_ln253_reg_824_pp0_iter4_reg, "select_ln253_reg_824_pp0_iter4_reg");
    sc_trace(mVcdFile, select_ln253_reg_824_pp0_iter5_reg, "select_ln253_reg_824_pp0_iter5_reg");
    sc_trace(mVcdFile, select_ln253_reg_824_pp0_iter6_reg, "select_ln253_reg_824_pp0_iter6_reg");
    sc_trace(mVcdFile, select_ln253_reg_824_pp0_iter7_reg, "select_ln253_reg_824_pp0_iter7_reg");
    sc_trace(mVcdFile, select_ln253_reg_824_pp0_iter8_reg, "select_ln253_reg_824_pp0_iter8_reg");
    sc_trace(mVcdFile, select_ln253_reg_824_pp0_iter9_reg, "select_ln253_reg_824_pp0_iter9_reg");
    sc_trace(mVcdFile, m_frac_l_V_fu_237_p3, "m_frac_l_V_fu_237_p3");
    sc_trace(mVcdFile, m_frac_l_V_reg_829, "m_frac_l_V_reg_829");
    sc_trace(mVcdFile, isNeg_fu_245_p3, "isNeg_fu_245_p3");
    sc_trace(mVcdFile, isNeg_reg_834, "isNeg_reg_834");
    sc_trace(mVcdFile, m_exp_2_fu_263_p3, "m_exp_2_fu_263_p3");
    sc_trace(mVcdFile, m_exp_2_reg_839, "m_exp_2_reg_839");
    sc_trace(mVcdFile, sext_ln1311_2_fu_271_p1, "sext_ln1311_2_fu_271_p1");
    sc_trace(mVcdFile, sext_ln1311_2_reg_844, "sext_ln1311_2_reg_844");
    sc_trace(mVcdFile, r_V_6_fu_303_p3, "r_V_6_fu_303_p3");
    sc_trace(mVcdFile, r_V_6_reg_849, "r_V_6_reg_849");
    sc_trace(mVcdFile, r_V_6_reg_849_pp0_iter1_reg, "r_V_6_reg_849_pp0_iter1_reg");
    sc_trace(mVcdFile, r_V_6_reg_849_pp0_iter2_reg, "r_V_6_reg_849_pp0_iter2_reg");
    sc_trace(mVcdFile, r_V_6_reg_849_pp0_iter3_reg, "r_V_6_reg_849_pp0_iter3_reg");
    sc_trace(mVcdFile, r_V_6_reg_849_pp0_iter4_reg, "r_V_6_reg_849_pp0_iter4_reg");
    sc_trace(mVcdFile, r_V_6_reg_849_pp0_iter5_reg, "r_V_6_reg_849_pp0_iter5_reg");
    sc_trace(mVcdFile, m_fix_l_V_reg_854, "m_fix_l_V_reg_854");
    sc_trace(mVcdFile, p_Result_13_reg_860, "p_Result_13_reg_860");
    sc_trace(mVcdFile, p_Result_13_reg_860_pp0_iter1_reg, "p_Result_13_reg_860_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln338_fu_343_p2, "icmp_ln338_fu_343_p2");
    sc_trace(mVcdFile, icmp_ln338_reg_870, "icmp_ln338_reg_870");
    sc_trace(mVcdFile, icmp_ln338_reg_870_pp0_iter1_reg, "icmp_ln338_reg_870_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln338_reg_870_pp0_iter2_reg, "icmp_ln338_reg_870_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln338_reg_870_pp0_iter3_reg, "icmp_ln338_reg_870_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln338_reg_870_pp0_iter4_reg, "icmp_ln338_reg_870_pp0_iter4_reg");
    sc_trace(mVcdFile, icmp_ln338_reg_870_pp0_iter5_reg, "icmp_ln338_reg_870_pp0_iter5_reg");
    sc_trace(mVcdFile, icmp_ln338_reg_870_pp0_iter6_reg, "icmp_ln338_reg_870_pp0_iter6_reg");
    sc_trace(mVcdFile, icmp_ln338_reg_870_pp0_iter7_reg, "icmp_ln338_reg_870_pp0_iter7_reg");
    sc_trace(mVcdFile, icmp_ln338_reg_870_pp0_iter8_reg, "icmp_ln338_reg_870_pp0_iter8_reg");
    sc_trace(mVcdFile, icmp_ln338_reg_870_pp0_iter9_reg, "icmp_ln338_reg_870_pp0_iter9_reg");
    sc_trace(mVcdFile, icmp_ln338_1_fu_383_p2, "icmp_ln338_1_fu_383_p2");
    sc_trace(mVcdFile, icmp_ln338_1_reg_878, "icmp_ln338_1_reg_878");
    sc_trace(mVcdFile, icmp_ln338_1_reg_878_pp0_iter2_reg, "icmp_ln338_1_reg_878_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln338_1_reg_878_pp0_iter3_reg, "icmp_ln338_1_reg_878_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln338_1_reg_878_pp0_iter4_reg, "icmp_ln338_1_reg_878_pp0_iter4_reg");
    sc_trace(mVcdFile, icmp_ln338_1_reg_878_pp0_iter5_reg, "icmp_ln338_1_reg_878_pp0_iter5_reg");
    sc_trace(mVcdFile, icmp_ln338_1_reg_878_pp0_iter6_reg, "icmp_ln338_1_reg_878_pp0_iter6_reg");
    sc_trace(mVcdFile, icmp_ln338_1_reg_878_pp0_iter7_reg, "icmp_ln338_1_reg_878_pp0_iter7_reg");
    sc_trace(mVcdFile, icmp_ln338_1_reg_878_pp0_iter8_reg, "icmp_ln338_1_reg_878_pp0_iter8_reg");
    sc_trace(mVcdFile, icmp_ln338_1_reg_878_pp0_iter9_reg, "icmp_ln338_1_reg_878_pp0_iter9_reg");
    sc_trace(mVcdFile, r_exp_V_3_fu_439_p3, "r_exp_V_3_fu_439_p3");
    sc_trace(mVcdFile, r_exp_V_3_reg_888, "r_exp_V_3_reg_888");
    sc_trace(mVcdFile, r_exp_V_3_reg_888_pp0_iter4_reg, "r_exp_V_3_reg_888_pp0_iter4_reg");
    sc_trace(mVcdFile, r_exp_V_3_reg_888_pp0_iter5_reg, "r_exp_V_3_reg_888_pp0_iter5_reg");
    sc_trace(mVcdFile, r_exp_V_3_reg_888_pp0_iter6_reg, "r_exp_V_3_reg_888_pp0_iter6_reg");
    sc_trace(mVcdFile, r_exp_V_3_reg_888_pp0_iter7_reg, "r_exp_V_3_reg_888_pp0_iter7_reg");
    sc_trace(mVcdFile, r_exp_V_3_reg_888_pp0_iter8_reg, "r_exp_V_3_reg_888_pp0_iter8_reg");
    sc_trace(mVcdFile, r_exp_V_3_reg_888_pp0_iter9_reg, "r_exp_V_3_reg_888_pp0_iter9_reg");
    sc_trace(mVcdFile, m_diff_lo_V_fu_491_p1, "m_diff_lo_V_fu_491_p1");
    sc_trace(mVcdFile, m_diff_lo_V_reg_899, "m_diff_lo_V_reg_899");
    sc_trace(mVcdFile, exp_Z1_V_reg_909, "exp_Z1_V_reg_909");
    sc_trace(mVcdFile, exp_Z1_V_reg_909_pp0_iter8_reg, "exp_Z1_V_reg_909_pp0_iter8_reg");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, zext_ln498_fu_495_p1, "zext_ln498_fu_495_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_149_p1, "p_Val2_s_fu_149_p1");
    sc_trace(mVcdFile, tmp_V_fu_161_p4, "tmp_V_fu_161_p4");
    sc_trace(mVcdFile, tmp_V_1_fu_171_p1, "tmp_V_1_fu_171_p1");
    sc_trace(mVcdFile, icmp_ln833_fu_175_p2, "icmp_ln833_fu_175_p2");
    sc_trace(mVcdFile, icmp_ln837_fu_181_p2, "icmp_ln837_fu_181_p2");
    sc_trace(mVcdFile, icmp_ln833_1_fu_193_p2, "icmp_ln833_1_fu_193_p2");
    sc_trace(mVcdFile, zext_ln659_fu_205_p1, "zext_ln659_fu_205_p1");
    sc_trace(mVcdFile, p_Result_s_fu_215_p3, "p_Result_s_fu_215_p3");
    sc_trace(mVcdFile, e_frac_V_fu_223_p2, "e_frac_V_fu_223_p2");
    sc_trace(mVcdFile, m_exp_fu_209_p2, "m_exp_fu_209_p2");
    sc_trace(mVcdFile, sub_ln1311_fu_253_p2, "sub_ln1311_fu_253_p2");
    sc_trace(mVcdFile, sext_ln1311_fu_259_p1, "sext_ln1311_fu_259_p1");
    sc_trace(mVcdFile, sext_ln1311_3_fu_275_p1, "sext_ln1311_3_fu_275_p1");
    sc_trace(mVcdFile, ashr_ln1287_fu_283_p2, "ashr_ln1287_fu_283_p2");
    sc_trace(mVcdFile, sext_ln1287_fu_279_p1, "sext_ln1287_fu_279_p1");
    sc_trace(mVcdFile, shl_ln1253_fu_293_p2, "shl_ln1253_fu_293_p2");
    sc_trace(mVcdFile, sext_ln1287_1_fu_289_p1, "sext_ln1287_1_fu_289_p1");
    sc_trace(mVcdFile, trunc_ln1310_fu_299_p1, "trunc_ln1310_fu_299_p1");
    sc_trace(mVcdFile, m_fix_hi_V_fu_321_p4, "m_fix_hi_V_fu_321_p4");
    sc_trace(mVcdFile, sext_ln1311_2cast_fu_355_p1, "sext_ln1311_2cast_fu_355_p1");
    sc_trace(mVcdFile, sext_ln1311_1_fu_349_p1, "sext_ln1311_1_fu_349_p1");
    sc_trace(mVcdFile, shl_ln1253_1_fu_358_p2, "shl_ln1253_1_fu_358_p2");
    sc_trace(mVcdFile, ashr_ln1287_1_fu_363_p2, "ashr_ln1287_1_fu_363_p2");
    sc_trace(mVcdFile, select_ln1322_fu_368_p3, "select_ln1322_fu_368_p3");
    sc_trace(mVcdFile, shl_ln_fu_375_p3, "shl_ln_fu_375_p3");
    sc_trace(mVcdFile, sext_ln1285_fu_352_p1, "sext_ln1285_fu_352_p1");
    sc_trace(mVcdFile, rhs_V_fu_389_p3, "rhs_V_fu_389_p3");
    sc_trace(mVcdFile, grp_fu_777_p3, "grp_fu_777_p3");
    sc_trace(mVcdFile, trunc_ln805_fu_416_p1, "trunc_ln805_fu_416_p1");
    sc_trace(mVcdFile, tmp_1_fu_400_p4, "tmp_1_fu_400_p4");
    sc_trace(mVcdFile, icmp_ln805_fu_419_p2, "icmp_ln805_fu_419_p2");
    sc_trace(mVcdFile, add_ln805_fu_425_p2, "add_ln805_fu_425_p2");
    sc_trace(mVcdFile, p_Result_7_fu_409_p3, "p_Result_7_fu_409_p3");
    sc_trace(mVcdFile, select_ln805_fu_431_p3, "select_ln805_fu_431_p3");
    sc_trace(mVcdFile, grp_fu_788_p2, "grp_fu_788_p2");
    sc_trace(mVcdFile, tmp_4_fu_454_p4, "tmp_4_fu_454_p4");
    sc_trace(mVcdFile, rhs_V_1_fu_463_p3, "rhs_V_1_fu_463_p3");
    sc_trace(mVcdFile, lhs_V_fu_451_p1, "lhs_V_fu_451_p1");
    sc_trace(mVcdFile, sext_ln682_1_fu_471_p1, "sext_ln682_1_fu_471_p1");
    sc_trace(mVcdFile, ret_V_3_fu_475_p2, "ret_V_3_fu_475_p2");
    sc_trace(mVcdFile, m_diff_hi_V_fu_481_p4, "m_diff_hi_V_fu_481_p4");
    sc_trace(mVcdFile, exp_Z1_hi_V_fu_500_p4, "exp_Z1_hi_V_fu_500_p4");
    sc_trace(mVcdFile, lhs_V_1_fu_517_p1, "lhs_V_1_fu_517_p1");
    sc_trace(mVcdFile, ret_V_4_fu_520_p2, "ret_V_4_fu_520_p2");
    sc_trace(mVcdFile, xor_ln936_fu_534_p2, "xor_ln936_fu_534_p2");
    sc_trace(mVcdFile, x_is_pinf_fu_539_p2, "x_is_pinf_fu_539_p2");
    sc_trace(mVcdFile, or_ln214_fu_544_p2, "or_ln214_fu_544_p2");
    sc_trace(mVcdFile, select_ln214_fu_549_p3, "select_ln214_fu_549_p3");
    sc_trace(mVcdFile, grp_fu_795_p3, "grp_fu_795_p3");
    sc_trace(mVcdFile, tmp_9_fu_568_p3, "tmp_9_fu_568_p3");
    sc_trace(mVcdFile, r_exp_V_fu_575_p2, "r_exp_V_fu_575_p2");
    sc_trace(mVcdFile, r_exp_V_2_fu_580_p3, "r_exp_V_2_fu_580_p3");
    sc_trace(mVcdFile, tmp_10_fu_587_p4, "tmp_10_fu_587_p4");
    sc_trace(mVcdFile, icmp_ln849_fu_597_p2, "icmp_ln849_fu_597_p2");
    sc_trace(mVcdFile, tmp_11_fu_608_p3, "tmp_11_fu_608_p3");
    sc_trace(mVcdFile, tmp_3_fu_638_p4, "tmp_3_fu_638_p4");
    sc_trace(mVcdFile, tmp_2_fu_629_p4, "tmp_2_fu_629_p4");
    sc_trace(mVcdFile, trunc_ln168_fu_655_p1, "trunc_ln168_fu_655_p1");
    sc_trace(mVcdFile, out_exp_V_fu_659_p2, "out_exp_V_fu_659_p2");
    sc_trace(mVcdFile, tmp_V_2_fu_647_p3, "tmp_V_2_fu_647_p3");
    sc_trace(mVcdFile, p_Result_14_fu_665_p4, "p_Result_14_fu_665_p4");
    sc_trace(mVcdFile, or_ln214_1_fu_556_p2, "or_ln214_1_fu_556_p2");
    sc_trace(mVcdFile, or_ln338_fu_603_p2, "or_ln338_fu_603_p2");
    sc_trace(mVcdFile, xor_ln338_fu_690_p2, "xor_ln338_fu_690_p2");
    sc_trace(mVcdFile, and_ln338_fu_685_p2, "and_ln338_fu_685_p2");
    sc_trace(mVcdFile, and_ln849_fu_695_p2, "and_ln849_fu_695_p2");
    sc_trace(mVcdFile, or_ln849_fu_701_p2, "or_ln849_fu_701_p2");
    sc_trace(mVcdFile, xor_ln214_fu_679_p2, "xor_ln214_fu_679_p2");
    sc_trace(mVcdFile, sel_tmp5_fu_707_p2, "sel_tmp5_fu_707_p2");
    sc_trace(mVcdFile, select_ln339_fu_615_p3, "select_ln339_fu_615_p3");
    sc_trace(mVcdFile, bitcast_ln667_fu_675_p1, "bitcast_ln667_fu_675_p1");
    sc_trace(mVcdFile, select_ln214_1_fu_560_p3, "select_ln214_1_fu_560_p3");
    sc_trace(mVcdFile, sel_tmp6_fu_713_p3, "sel_tmp6_fu_713_p3");
    sc_trace(mVcdFile, xor_ln338_1_fu_729_p2, "xor_ln338_1_fu_729_p2");
    sc_trace(mVcdFile, or_ln849_1_fu_740_p2, "or_ln849_1_fu_740_p2");
    sc_trace(mVcdFile, and_ln338_1_fu_735_p2, "and_ln338_1_fu_735_p2");
    sc_trace(mVcdFile, xor_ln849_fu_745_p2, "xor_ln849_fu_745_p2");
    sc_trace(mVcdFile, or_ln849_2_fu_751_p2, "or_ln849_2_fu_751_p2");
    sc_trace(mVcdFile, tmp_fu_757_p2, "tmp_fu_757_p2");
    sc_trace(mVcdFile, icmp_ln853_fu_623_p2, "icmp_ln853_fu_623_p2");
    sc_trace(mVcdFile, sel_tmp16_fu_763_p2, "sel_tmp16_fu_763_p2");
    sc_trace(mVcdFile, select_ln214_2_fu_721_p3, "select_ln214_2_fu_721_p3");
    sc_trace(mVcdFile, grp_fu_777_p0, "grp_fu_777_p0");
    sc_trace(mVcdFile, grp_fu_788_p0, "grp_fu_788_p0");
    sc_trace(mVcdFile, grp_fu_795_p0, "grp_fu_795_p0");
    sc_trace(mVcdFile, grp_fu_795_p1, "grp_fu_795_p1");
    sc_trace(mVcdFile, grp_fu_795_p2, "grp_fu_795_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to9, "ap_idle_pp0_0to9");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, grp_fu_795_p00, "grp_fu_795_p00");
    sc_trace(mVcdFile, grp_fu_795_p10, "grp_fu_795_p10");
#endif

    }
}

exp_generic_decimal16_s::~exp_generic_decimal16_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_U;
    delete calcPerceptron_mac_muladd_10ns_10s_13s_19_4_1_U1;
    delete calcPerceptron_mul_mul_20ns_7s_26_4_1_U2;
    delete calcPerceptron_mac_muladd_4ns_5ns_19ns_19_4_1_U3;
}

void exp_generic_decimal16_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void exp_generic_decimal16_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        and_ln18_reg_818 = and_ln18_fu_199_p2.read();
        and_ln18_reg_818_pp0_iter1_reg = and_ln18_reg_818.read();
        and_ln209_reg_811 = and_ln209_fu_187_p2.read();
        and_ln209_reg_811_pp0_iter1_reg = and_ln209_reg_811.read();
        icmp_ln338_1_reg_878 = icmp_ln338_1_fu_383_p2.read();
        icmp_ln338_reg_870 = icmp_ln338_fu_343_p2.read();
        icmp_ln338_reg_870_pp0_iter1_reg = icmp_ln338_reg_870.read();
        isNeg_reg_834 = m_exp_fu_209_p2.read().range(5, 5);
        m_exp_2_reg_839 = m_exp_2_fu_263_p3.read();
        m_fix_l_V_reg_854 = r_V_6_fu_303_p3.read().range(18, 3);
        m_frac_l_V_reg_829 = m_frac_l_V_fu_237_p3.read();
        p_Result_12_reg_806 = p_Val2_s_fu_149_p1.read().range(15, 15);
        p_Result_12_reg_806_pp0_iter1_reg = p_Result_12_reg_806.read();
        p_Result_13_reg_860 = r_V_6_fu_303_p3.read().range(18, 18);
        p_Result_13_reg_860_pp0_iter1_reg = p_Result_13_reg_860.read();
        r_V_6_reg_849 = r_V_6_fu_303_p3.read();
        r_V_6_reg_849_pp0_iter1_reg = r_V_6_reg_849.read();
        select_ln253_reg_824 = select_ln253_fu_229_p3.read();
        select_ln253_reg_824_pp0_iter1_reg = select_ln253_reg_824.read();
        sext_ln1311_2_reg_844 = sext_ln1311_2_fu_271_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        and_ln18_reg_818_pp0_iter2_reg = and_ln18_reg_818_pp0_iter1_reg.read();
        and_ln18_reg_818_pp0_iter3_reg = and_ln18_reg_818_pp0_iter2_reg.read();
        and_ln18_reg_818_pp0_iter4_reg = and_ln18_reg_818_pp0_iter3_reg.read();
        and_ln18_reg_818_pp0_iter5_reg = and_ln18_reg_818_pp0_iter4_reg.read();
        and_ln18_reg_818_pp0_iter6_reg = and_ln18_reg_818_pp0_iter5_reg.read();
        and_ln18_reg_818_pp0_iter7_reg = and_ln18_reg_818_pp0_iter6_reg.read();
        and_ln18_reg_818_pp0_iter8_reg = and_ln18_reg_818_pp0_iter7_reg.read();
        and_ln18_reg_818_pp0_iter9_reg = and_ln18_reg_818_pp0_iter8_reg.read();
        and_ln209_reg_811_pp0_iter2_reg = and_ln209_reg_811_pp0_iter1_reg.read();
        and_ln209_reg_811_pp0_iter3_reg = and_ln209_reg_811_pp0_iter2_reg.read();
        and_ln209_reg_811_pp0_iter4_reg = and_ln209_reg_811_pp0_iter3_reg.read();
        and_ln209_reg_811_pp0_iter5_reg = and_ln209_reg_811_pp0_iter4_reg.read();
        and_ln209_reg_811_pp0_iter6_reg = and_ln209_reg_811_pp0_iter5_reg.read();
        and_ln209_reg_811_pp0_iter7_reg = and_ln209_reg_811_pp0_iter6_reg.read();
        and_ln209_reg_811_pp0_iter8_reg = and_ln209_reg_811_pp0_iter7_reg.read();
        and_ln209_reg_811_pp0_iter9_reg = and_ln209_reg_811_pp0_iter8_reg.read();
        exp_Z1_V_reg_909 = table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0.read();
        exp_Z1_V_reg_909_pp0_iter8_reg = exp_Z1_V_reg_909.read();
        icmp_ln338_1_reg_878_pp0_iter2_reg = icmp_ln338_1_reg_878.read();
        icmp_ln338_1_reg_878_pp0_iter3_reg = icmp_ln338_1_reg_878_pp0_iter2_reg.read();
        icmp_ln338_1_reg_878_pp0_iter4_reg = icmp_ln338_1_reg_878_pp0_iter3_reg.read();
        icmp_ln338_1_reg_878_pp0_iter5_reg = icmp_ln338_1_reg_878_pp0_iter4_reg.read();
        icmp_ln338_1_reg_878_pp0_iter6_reg = icmp_ln338_1_reg_878_pp0_iter5_reg.read();
        icmp_ln338_1_reg_878_pp0_iter7_reg = icmp_ln338_1_reg_878_pp0_iter6_reg.read();
        icmp_ln338_1_reg_878_pp0_iter8_reg = icmp_ln338_1_reg_878_pp0_iter7_reg.read();
        icmp_ln338_1_reg_878_pp0_iter9_reg = icmp_ln338_1_reg_878_pp0_iter8_reg.read();
        icmp_ln338_reg_870_pp0_iter2_reg = icmp_ln338_reg_870_pp0_iter1_reg.read();
        icmp_ln338_reg_870_pp0_iter3_reg = icmp_ln338_reg_870_pp0_iter2_reg.read();
        icmp_ln338_reg_870_pp0_iter4_reg = icmp_ln338_reg_870_pp0_iter3_reg.read();
        icmp_ln338_reg_870_pp0_iter5_reg = icmp_ln338_reg_870_pp0_iter4_reg.read();
        icmp_ln338_reg_870_pp0_iter6_reg = icmp_ln338_reg_870_pp0_iter5_reg.read();
        icmp_ln338_reg_870_pp0_iter7_reg = icmp_ln338_reg_870_pp0_iter6_reg.read();
        icmp_ln338_reg_870_pp0_iter8_reg = icmp_ln338_reg_870_pp0_iter7_reg.read();
        icmp_ln338_reg_870_pp0_iter9_reg = icmp_ln338_reg_870_pp0_iter8_reg.read();
        m_diff_lo_V_reg_899 = m_diff_lo_V_fu_491_p1.read();
        p_Result_12_reg_806_pp0_iter2_reg = p_Result_12_reg_806_pp0_iter1_reg.read();
        p_Result_12_reg_806_pp0_iter3_reg = p_Result_12_reg_806_pp0_iter2_reg.read();
        p_Result_12_reg_806_pp0_iter4_reg = p_Result_12_reg_806_pp0_iter3_reg.read();
        p_Result_12_reg_806_pp0_iter5_reg = p_Result_12_reg_806_pp0_iter4_reg.read();
        p_Result_12_reg_806_pp0_iter6_reg = p_Result_12_reg_806_pp0_iter5_reg.read();
        p_Result_12_reg_806_pp0_iter7_reg = p_Result_12_reg_806_pp0_iter6_reg.read();
        p_Result_12_reg_806_pp0_iter8_reg = p_Result_12_reg_806_pp0_iter7_reg.read();
        p_Result_12_reg_806_pp0_iter9_reg = p_Result_12_reg_806_pp0_iter8_reg.read();
        r_V_6_reg_849_pp0_iter2_reg = r_V_6_reg_849_pp0_iter1_reg.read();
        r_V_6_reg_849_pp0_iter3_reg = r_V_6_reg_849_pp0_iter2_reg.read();
        r_V_6_reg_849_pp0_iter4_reg = r_V_6_reg_849_pp0_iter3_reg.read();
        r_V_6_reg_849_pp0_iter5_reg = r_V_6_reg_849_pp0_iter4_reg.read();
        r_exp_V_3_reg_888 = r_exp_V_3_fu_439_p3.read();
        r_exp_V_3_reg_888_pp0_iter4_reg = r_exp_V_3_reg_888.read();
        r_exp_V_3_reg_888_pp0_iter5_reg = r_exp_V_3_reg_888_pp0_iter4_reg.read();
        r_exp_V_3_reg_888_pp0_iter6_reg = r_exp_V_3_reg_888_pp0_iter5_reg.read();
        r_exp_V_3_reg_888_pp0_iter7_reg = r_exp_V_3_reg_888_pp0_iter6_reg.read();
        r_exp_V_3_reg_888_pp0_iter8_reg = r_exp_V_3_reg_888_pp0_iter7_reg.read();
        r_exp_V_3_reg_888_pp0_iter9_reg = r_exp_V_3_reg_888_pp0_iter8_reg.read();
        select_ln253_reg_824_pp0_iter2_reg = select_ln253_reg_824_pp0_iter1_reg.read();
        select_ln253_reg_824_pp0_iter3_reg = select_ln253_reg_824_pp0_iter2_reg.read();
        select_ln253_reg_824_pp0_iter4_reg = select_ln253_reg_824_pp0_iter3_reg.read();
        select_ln253_reg_824_pp0_iter5_reg = select_ln253_reg_824_pp0_iter4_reg.read();
        select_ln253_reg_824_pp0_iter6_reg = select_ln253_reg_824_pp0_iter5_reg.read();
        select_ln253_reg_824_pp0_iter7_reg = select_ln253_reg_824_pp0_iter6_reg.read();
        select_ln253_reg_824_pp0_iter8_reg = select_ln253_reg_824_pp0_iter7_reg.read();
        select_ln253_reg_824_pp0_iter9_reg = select_ln253_reg_824_pp0_iter8_reg.read();
    }
}

void exp_generic_decimal16_s::thread_add_ln805_fu_425_p2() {
    add_ln805_fu_425_p2 = (!ap_const_lv7_1.is_01() || !tmp_1_fu_400_p4.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_1) + sc_biguint<7>(tmp_1_fu_400_p4.read()));
}

void exp_generic_decimal16_s::thread_and_ln18_fu_199_p2() {
    and_ln18_fu_199_p2 = (icmp_ln833_fu_175_p2.read() & icmp_ln833_1_fu_193_p2.read());
}

void exp_generic_decimal16_s::thread_and_ln209_fu_187_p2() {
    and_ln209_fu_187_p2 = (icmp_ln833_fu_175_p2.read() & icmp_ln837_fu_181_p2.read());
}

void exp_generic_decimal16_s::thread_and_ln338_1_fu_735_p2() {
    and_ln338_1_fu_735_p2 = (icmp_ln338_reg_870_pp0_iter9_reg.read() & xor_ln338_1_fu_729_p2.read());
}

void exp_generic_decimal16_s::thread_and_ln338_fu_685_p2() {
    and_ln338_fu_685_p2 = (icmp_ln338_reg_870_pp0_iter9_reg.read() & or_ln338_fu_603_p2.read());
}

void exp_generic_decimal16_s::thread_and_ln849_fu_695_p2() {
    and_ln849_fu_695_p2 = (icmp_ln849_fu_597_p2.read() & xor_ln338_fu_690_p2.read());
}

void exp_generic_decimal16_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void exp_generic_decimal16_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_decimal16_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()));
}

void exp_generic_decimal16_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()));
}

void exp_generic_decimal16_s::thread_ap_block_state10_pp0_stage0_iter9() {
    ap_block_state10_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_decimal16_s::thread_ap_block_state11_pp0_stage0_iter10() {
    ap_block_state11_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_decimal16_s::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read());
}

void exp_generic_decimal16_s::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_decimal16_s::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_decimal16_s::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_decimal16_s::thread_ap_block_state5_pp0_stage0_iter4() {
    ap_block_state5_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_decimal16_s::thread_ap_block_state6_pp0_stage0_iter5() {
    ap_block_state6_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_decimal16_s::thread_ap_block_state7_pp0_stage0_iter6() {
    ap_block_state7_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_decimal16_s::thread_ap_block_state8_pp0_stage0_iter7() {
    ap_block_state8_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_decimal16_s::thread_ap_block_state9_pp0_stage0_iter8() {
    ap_block_state9_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void exp_generic_decimal16_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void exp_generic_decimal16_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void exp_generic_decimal16_s::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void exp_generic_decimal16_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void exp_generic_decimal16_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void exp_generic_decimal16_s::thread_ap_idle_pp0_0to9() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()))) {
        ap_idle_pp0_0to9 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to9 = ap_const_logic_0;
    }
}

void exp_generic_decimal16_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void exp_generic_decimal16_s::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to9.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void exp_generic_decimal16_s::thread_ap_return() {
    ap_return = (!sel_tmp16_fu_763_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp16_fu_763_p2.read()[0].to_bool())? ap_const_lv16_0: select_ln214_2_fu_721_p3.read());
}

void exp_generic_decimal16_s::thread_ashr_ln1287_1_fu_363_p2() {
    ashr_ln1287_1_fu_363_p2 = (!m_fix_l_V_reg_854.read().is_01() || !sext_ln1311_1_fu_349_p1.read().is_01())? sc_lv<16>(): sc_bigint<16>(m_fix_l_V_reg_854.read()) >> (unsigned short)sext_ln1311_1_fu_349_p1.read().to_uint();
}

void exp_generic_decimal16_s::thread_ashr_ln1287_fu_283_p2() {
    ashr_ln1287_fu_283_p2 = (!m_frac_l_V_fu_237_p3.read().is_01() || !sext_ln1311_3_fu_275_p1.read().is_01())? sc_lv<15>(): sc_bigint<15>(m_frac_l_V_fu_237_p3.read()) >> (unsigned short)sext_ln1311_3_fu_275_p1.read().to_uint();
}

void exp_generic_decimal16_s::thread_bitcast_ln667_fu_675_p1() {
    bitcast_ln667_fu_675_p1 = p_Result_14_fu_665_p4.read();
}

void exp_generic_decimal16_s::thread_e_frac_V_fu_223_p2() {
    e_frac_V_fu_223_p2 = (!ap_const_lv12_0.is_01() || !p_Result_s_fu_215_p3.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_biguint<12>(p_Result_s_fu_215_p3.read()));
}

void exp_generic_decimal16_s::thread_exp_Z1_hi_V_fu_500_p4() {
    exp_Z1_hi_V_fu_500_p4 = table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0.read().range(13, 9);
}

void exp_generic_decimal16_s::thread_grp_fu_777_p0() {
    grp_fu_777_p0 =  (sc_lv<10>) (ap_const_lv19_171);
}

void exp_generic_decimal16_s::thread_grp_fu_788_p0() {
    grp_fu_788_p0 =  (sc_lv<20>) (ap_const_lv26_58B90);
}

void exp_generic_decimal16_s::thread_grp_fu_795_p0() {
    grp_fu_795_p0 =  (sc_lv<4>) (grp_fu_795_p00.read());
}

void exp_generic_decimal16_s::thread_grp_fu_795_p00() {
    grp_fu_795_p00 = esl_zext<9,4>(m_diff_lo_V_reg_899.read());
}

void exp_generic_decimal16_s::thread_grp_fu_795_p1() {
    grp_fu_795_p1 =  (sc_lv<5>) (grp_fu_795_p10.read());
}

void exp_generic_decimal16_s::thread_grp_fu_795_p10() {
    grp_fu_795_p10 = esl_zext<9,5>(exp_Z1_hi_V_fu_500_p4.read());
}

void exp_generic_decimal16_s::thread_grp_fu_795_p2() {
    grp_fu_795_p2 = esl_concat<15,4>(ret_V_4_fu_520_p2.read(), ap_const_lv4_0);
}

void exp_generic_decimal16_s::thread_icmp_ln338_1_fu_383_p2() {
    icmp_ln338_1_fu_383_p2 = (!shl_ln_fu_375_p3.read().is_01() || !sext_ln1285_fu_352_p1.read().is_01())? sc_lv<1>(): sc_lv<1>(shl_ln_fu_375_p3.read() != sext_ln1285_fu_352_p1.read());
}

void exp_generic_decimal16_s::thread_icmp_ln338_fu_343_p2() {
    icmp_ln338_fu_343_p2 = (!m_exp_fu_209_p2.read().is_01() || !ap_const_lv6_0.is_01())? sc_lv<1>(): (sc_bigint<6>(m_exp_fu_209_p2.read()) > sc_bigint<6>(ap_const_lv6_0));
}

void exp_generic_decimal16_s::thread_icmp_ln805_fu_419_p2() {
    icmp_ln805_fu_419_p2 = (!trunc_ln805_fu_416_p1.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln805_fu_416_p1.read() == ap_const_lv12_0);
}

void exp_generic_decimal16_s::thread_icmp_ln833_1_fu_193_p2() {
    icmp_ln833_1_fu_193_p2 = (!tmp_V_1_fu_171_p1.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_1_fu_171_p1.read() == ap_const_lv10_0);
}

void exp_generic_decimal16_s::thread_icmp_ln833_fu_175_p2() {
    icmp_ln833_fu_175_p2 = (!tmp_V_fu_161_p4.read().is_01() || !ap_const_lv5_1F.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_fu_161_p4.read() == ap_const_lv5_1F);
}

void exp_generic_decimal16_s::thread_icmp_ln837_fu_181_p2() {
    icmp_ln837_fu_181_p2 = (!tmp_V_1_fu_171_p1.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_1_fu_171_p1.read() != ap_const_lv10_0);
}

void exp_generic_decimal16_s::thread_icmp_ln849_fu_597_p2() {
    icmp_ln849_fu_597_p2 = (!tmp_10_fu_587_p4.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): (sc_bigint<3>(tmp_10_fu_587_p4.read()) > sc_bigint<3>(ap_const_lv3_0));
}

void exp_generic_decimal16_s::thread_icmp_ln853_fu_623_p2() {
    icmp_ln853_fu_623_p2 = (!r_exp_V_2_fu_580_p3.read().is_01() || !ap_const_lv7_72.is_01())? sc_lv<1>(): (sc_bigint<7>(r_exp_V_2_fu_580_p3.read()) < sc_bigint<7>(ap_const_lv7_72));
}

void exp_generic_decimal16_s::thread_isNeg_fu_245_p3() {
    isNeg_fu_245_p3 = m_exp_fu_209_p2.read().range(5, 5);
}

void exp_generic_decimal16_s::thread_lhs_V_1_fu_517_p1() {
    lhs_V_1_fu_517_p1 = esl_zext<15,14>(exp_Z1_V_reg_909_pp0_iter8_reg.read());
}

void exp_generic_decimal16_s::thread_lhs_V_fu_451_p1() {
    lhs_V_fu_451_p1 = esl_sext<21,19>(r_V_6_reg_849_pp0_iter5_reg.read());
}

void exp_generic_decimal16_s::thread_m_diff_hi_V_fu_481_p4() {
    m_diff_hi_V_fu_481_p4 = ret_V_3_fu_475_p2.read().range(12, 4);
}

void exp_generic_decimal16_s::thread_m_diff_lo_V_fu_491_p1() {
    m_diff_lo_V_fu_491_p1 = ret_V_3_fu_475_p2.read().range(4-1, 0);
}

void exp_generic_decimal16_s::thread_m_exp_2_fu_263_p3() {
    m_exp_2_fu_263_p3 = (!isNeg_fu_245_p3.read()[0].is_01())? sc_lv<6>(): ((isNeg_fu_245_p3.read()[0].to_bool())? sext_ln1311_fu_259_p1.read(): m_exp_fu_209_p2.read());
}

void exp_generic_decimal16_s::thread_m_exp_fu_209_p2() {
    m_exp_fu_209_p2 = (!ap_const_lv6_31.is_01() || !zext_ln659_fu_205_p1.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_31) + sc_biguint<6>(zext_ln659_fu_205_p1.read()));
}

void exp_generic_decimal16_s::thread_m_fix_hi_V_fu_321_p4() {
    m_fix_hi_V_fu_321_p4 = r_V_6_fu_303_p3.read().range(18, 9);
}

void exp_generic_decimal16_s::thread_m_frac_l_V_fu_237_p3() {
    m_frac_l_V_fu_237_p3 = esl_concat<12,3>(select_ln253_fu_229_p3.read(), ap_const_lv3_0);
}

void exp_generic_decimal16_s::thread_or_ln214_1_fu_556_p2() {
    or_ln214_1_fu_556_p2 = (and_ln209_reg_811_pp0_iter9_reg.read() | and_ln18_reg_818_pp0_iter9_reg.read());
}

void exp_generic_decimal16_s::thread_or_ln214_fu_544_p2() {
    or_ln214_fu_544_p2 = (and_ln209_reg_811_pp0_iter9_reg.read() | x_is_pinf_fu_539_p2.read());
}

void exp_generic_decimal16_s::thread_or_ln338_fu_603_p2() {
    or_ln338_fu_603_p2 = (icmp_ln338_1_reg_878_pp0_iter9_reg.read() | icmp_ln849_fu_597_p2.read());
}

void exp_generic_decimal16_s::thread_or_ln849_1_fu_740_p2() {
    or_ln849_1_fu_740_p2 = (icmp_ln338_reg_870_pp0_iter9_reg.read() | icmp_ln849_fu_597_p2.read());
}

void exp_generic_decimal16_s::thread_or_ln849_2_fu_751_p2() {
    or_ln849_2_fu_751_p2 = (and_ln338_1_fu_735_p2.read() | xor_ln849_fu_745_p2.read());
}

void exp_generic_decimal16_s::thread_or_ln849_fu_701_p2() {
    or_ln849_fu_701_p2 = (and_ln338_fu_685_p2.read() | and_ln849_fu_695_p2.read());
}

void exp_generic_decimal16_s::thread_out_exp_V_fu_659_p2() {
    out_exp_V_fu_659_p2 = (!ap_const_lv5_F.is_01() || !trunc_ln168_fu_655_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_F) + sc_biguint<5>(trunc_ln168_fu_655_p1.read()));
}

void exp_generic_decimal16_s::thread_p_Result_12_fu_153_p3() {
    p_Result_12_fu_153_p3 = p_Val2_s_fu_149_p1.read().range(15, 15);
}

void exp_generic_decimal16_s::thread_p_Result_14_fu_665_p4() {
    p_Result_14_fu_665_p4 = esl_concat<6,10>(esl_concat<1,5>(ap_const_lv1_0, out_exp_V_fu_659_p2.read()), tmp_V_2_fu_647_p3.read());
}

void exp_generic_decimal16_s::thread_p_Result_7_fu_409_p3() {
    p_Result_7_fu_409_p3 = grp_fu_777_p3.read().range(18, 18);
}

void exp_generic_decimal16_s::thread_p_Result_s_fu_215_p3() {
    p_Result_s_fu_215_p3 = esl_concat<2,10>(ap_const_lv2_1, tmp_V_1_fu_171_p1.read());
}

void exp_generic_decimal16_s::thread_p_Val2_s_fu_149_p1() {
    p_Val2_s_fu_149_p1 = x.read();
}

void exp_generic_decimal16_s::thread_r_V_6_fu_303_p3() {
    r_V_6_fu_303_p3 = (!isNeg_fu_245_p3.read()[0].is_01())? sc_lv<19>(): ((isNeg_fu_245_p3.read()[0].to_bool())? sext_ln1287_1_fu_289_p1.read(): trunc_ln1310_fu_299_p1.read());
}

void exp_generic_decimal16_s::thread_r_exp_V_2_fu_580_p3() {
    r_exp_V_2_fu_580_p3 = (!tmp_9_fu_568_p3.read()[0].is_01())? sc_lv<7>(): ((tmp_9_fu_568_p3.read()[0].to_bool())? r_exp_V_3_reg_888_pp0_iter9_reg.read(): r_exp_V_fu_575_p2.read());
}

void exp_generic_decimal16_s::thread_r_exp_V_3_fu_439_p3() {
    r_exp_V_3_fu_439_p3 = (!p_Result_7_fu_409_p3.read()[0].is_01())? sc_lv<7>(): ((p_Result_7_fu_409_p3.read()[0].to_bool())? select_ln805_fu_431_p3.read(): tmp_1_fu_400_p4.read());
}

void exp_generic_decimal16_s::thread_r_exp_V_fu_575_p2() {
    r_exp_V_fu_575_p2 = (!ap_const_lv7_7F.is_01() || !r_exp_V_3_reg_888_pp0_iter9_reg.read().is_01())? sc_lv<7>(): (sc_bigint<7>(ap_const_lv7_7F) + sc_bigint<7>(r_exp_V_3_reg_888_pp0_iter9_reg.read()));
}

void exp_generic_decimal16_s::thread_ret_V_3_fu_475_p2() {
    ret_V_3_fu_475_p2 = (!lhs_V_fu_451_p1.read().is_01() || !sext_ln682_1_fu_471_p1.read().is_01())? sc_lv<21>(): (sc_bigint<21>(lhs_V_fu_451_p1.read()) - sc_bigint<21>(sext_ln682_1_fu_471_p1.read()));
}

void exp_generic_decimal16_s::thread_ret_V_4_fu_520_p2() {
    ret_V_4_fu_520_p2 = (!ap_const_lv15_4.is_01() || !lhs_V_1_fu_517_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(ap_const_lv15_4) + sc_biguint<15>(lhs_V_1_fu_517_p1.read()));
}

void exp_generic_decimal16_s::thread_rhs_V_1_fu_463_p3() {
    rhs_V_1_fu_463_p3 = esl_concat<19,1>(tmp_4_fu_454_p4.read(), ap_const_lv1_0);
}

void exp_generic_decimal16_s::thread_rhs_V_fu_389_p3() {
    rhs_V_fu_389_p3 = esl_concat<1,12>(p_Result_13_reg_860_pp0_iter1_reg.read(), ap_const_lv12_800);
}

void exp_generic_decimal16_s::thread_sel_tmp16_fu_763_p2() {
    sel_tmp16_fu_763_p2 = (tmp_fu_757_p2.read() & icmp_ln853_fu_623_p2.read());
}

void exp_generic_decimal16_s::thread_sel_tmp5_fu_707_p2() {
    sel_tmp5_fu_707_p2 = (or_ln849_fu_701_p2.read() & xor_ln214_fu_679_p2.read());
}

void exp_generic_decimal16_s::thread_sel_tmp6_fu_713_p3() {
    sel_tmp6_fu_713_p3 = (!sel_tmp5_fu_707_p2.read()[0].is_01())? sc_lv<16>(): ((sel_tmp5_fu_707_p2.read()[0].to_bool())? select_ln339_fu_615_p3.read(): bitcast_ln667_fu_675_p1.read());
}

void exp_generic_decimal16_s::thread_select_ln1322_fu_368_p3() {
    select_ln1322_fu_368_p3 = (!isNeg_reg_834.read()[0].is_01())? sc_lv<16>(): ((isNeg_reg_834.read()[0].to_bool())? shl_ln1253_1_fu_358_p2.read(): ashr_ln1287_1_fu_363_p2.read());
}

void exp_generic_decimal16_s::thread_select_ln214_1_fu_560_p3() {
    select_ln214_1_fu_560_p3 = (!or_ln214_fu_544_p2.read()[0].is_01())? sc_lv<16>(): ((or_ln214_fu_544_p2.read()[0].to_bool())? select_ln214_fu_549_p3.read(): ap_const_lv16_0);
}

void exp_generic_decimal16_s::thread_select_ln214_2_fu_721_p3() {
    select_ln214_2_fu_721_p3 = (!or_ln214_1_fu_556_p2.read()[0].is_01())? sc_lv<16>(): ((or_ln214_1_fu_556_p2.read()[0].to_bool())? select_ln214_1_fu_560_p3.read(): sel_tmp6_fu_713_p3.read());
}

void exp_generic_decimal16_s::thread_select_ln214_fu_549_p3() {
    select_ln214_fu_549_p3 = (!and_ln209_reg_811_pp0_iter9_reg.read()[0].is_01())? sc_lv<16>(): ((and_ln209_reg_811_pp0_iter9_reg.read()[0].to_bool())? ap_const_lv16_7FFF: ap_const_lv16_7C00);
}

void exp_generic_decimal16_s::thread_select_ln253_fu_229_p3() {
    select_ln253_fu_229_p3 = (!p_Result_12_fu_153_p3.read()[0].is_01())? sc_lv<12>(): ((p_Result_12_fu_153_p3.read()[0].to_bool())? e_frac_V_fu_223_p2.read(): p_Result_s_fu_215_p3.read());
}

void exp_generic_decimal16_s::thread_select_ln339_fu_615_p3() {
    select_ln339_fu_615_p3 = (!tmp_11_fu_608_p3.read()[0].is_01())? sc_lv<16>(): ((tmp_11_fu_608_p3.read()[0].to_bool())? ap_const_lv16_0: ap_const_lv16_7C00);
}

void exp_generic_decimal16_s::thread_select_ln805_fu_431_p3() {
    select_ln805_fu_431_p3 = (!icmp_ln805_fu_419_p2.read()[0].is_01())? sc_lv<7>(): ((icmp_ln805_fu_419_p2.read()[0].to_bool())? tmp_1_fu_400_p4.read(): add_ln805_fu_425_p2.read());
}

void exp_generic_decimal16_s::thread_sext_ln1285_fu_352_p1() {
    sext_ln1285_fu_352_p1 = esl_sext<19,15>(m_frac_l_V_reg_829.read());
}

void exp_generic_decimal16_s::thread_sext_ln1287_1_fu_289_p1() {
    sext_ln1287_1_fu_289_p1 = esl_sext<19,15>(ashr_ln1287_fu_283_p2.read());
}

void exp_generic_decimal16_s::thread_sext_ln1287_fu_279_p1() {
    sext_ln1287_fu_279_p1 = esl_sext<32,15>(m_frac_l_V_fu_237_p3.read());
}

void exp_generic_decimal16_s::thread_sext_ln1311_1_fu_349_p1() {
    sext_ln1311_1_fu_349_p1 = esl_sext<16,6>(m_exp_2_reg_839.read());
}

void exp_generic_decimal16_s::thread_sext_ln1311_2_fu_271_p1() {
    sext_ln1311_2_fu_271_p1 = esl_sext<32,6>(m_exp_2_fu_263_p3.read());
}

void exp_generic_decimal16_s::thread_sext_ln1311_2cast_fu_355_p1() {
    sext_ln1311_2cast_fu_355_p1 = sext_ln1311_2_reg_844.read().range(16-1, 0);
}

void exp_generic_decimal16_s::thread_sext_ln1311_3_fu_275_p1() {
    sext_ln1311_3_fu_275_p1 = esl_sext<15,6>(m_exp_2_fu_263_p3.read());
}

void exp_generic_decimal16_s::thread_sext_ln1311_fu_259_p1() {
    sext_ln1311_fu_259_p1 = esl_sext<6,5>(sub_ln1311_fu_253_p2.read());
}

void exp_generic_decimal16_s::thread_sext_ln682_1_fu_471_p1() {
    sext_ln682_1_fu_471_p1 = esl_sext<21,20>(rhs_V_1_fu_463_p3.read());
}

void exp_generic_decimal16_s::thread_shl_ln1253_1_fu_358_p2() {
    shl_ln1253_1_fu_358_p2 = (!sext_ln1311_2cast_fu_355_p1.read().is_01())? sc_lv<16>(): m_fix_l_V_reg_854.read() << (unsigned short)sext_ln1311_2cast_fu_355_p1.read().to_uint();
}

void exp_generic_decimal16_s::thread_shl_ln1253_fu_293_p2() {
    shl_ln1253_fu_293_p2 = (!sext_ln1311_2_fu_271_p1.read().is_01())? sc_lv<32>(): sext_ln1287_fu_279_p1.read() << (unsigned short)sext_ln1311_2_fu_271_p1.read().to_uint();
}

void exp_generic_decimal16_s::thread_shl_ln_fu_375_p3() {
    shl_ln_fu_375_p3 = esl_concat<16,3>(select_ln1322_fu_368_p3.read(), ap_const_lv3_0);
}

void exp_generic_decimal16_s::thread_sub_ln1311_fu_253_p2() {
    sub_ln1311_fu_253_p2 = (!ap_const_lv5_F.is_01() || !tmp_V_fu_161_p4.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_F) - sc_biguint<5>(tmp_V_fu_161_p4.read()));
}

void exp_generic_decimal16_s::thread_table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0() {
    table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 =  (sc_lv<9>) (zext_ln498_fu_495_p1.read());
}

void exp_generic_decimal16_s::thread_table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()))) {
        table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = ap_const_logic_1;
    } else {
        table_exp_Z1_ap_ufixed_14_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = ap_const_logic_0;
    }
}

void exp_generic_decimal16_s::thread_tmp_10_fu_587_p4() {
    tmp_10_fu_587_p4 = r_exp_V_2_fu_580_p3.read().range(6, 4);
}

void exp_generic_decimal16_s::thread_tmp_11_fu_608_p3() {
    tmp_11_fu_608_p3 = select_ln253_reg_824_pp0_iter9_reg.read().range(11, 11);
}

void exp_generic_decimal16_s::thread_tmp_1_fu_400_p4() {
    tmp_1_fu_400_p4 = grp_fu_777_p3.read().range(18, 12);
}

void exp_generic_decimal16_s::thread_tmp_2_fu_629_p4() {
    tmp_2_fu_629_p4 = grp_fu_795_p3.read().range(15, 6);
}

void exp_generic_decimal16_s::thread_tmp_3_fu_638_p4() {
    tmp_3_fu_638_p4 = grp_fu_795_p3.read().range(16, 7);
}

void exp_generic_decimal16_s::thread_tmp_4_fu_454_p4() {
    tmp_4_fu_454_p4 = grp_fu_788_p2.read().range(25, 7);
}

void exp_generic_decimal16_s::thread_tmp_9_fu_568_p3() {
    tmp_9_fu_568_p3 = grp_fu_795_p3.read().range(17, 17);
}

void exp_generic_decimal16_s::thread_tmp_V_1_fu_171_p1() {
    tmp_V_1_fu_171_p1 = p_Val2_s_fu_149_p1.read().range(10-1, 0);
}

void exp_generic_decimal16_s::thread_tmp_V_2_fu_647_p3() {
    tmp_V_2_fu_647_p3 = (!tmp_9_fu_568_p3.read()[0].is_01())? sc_lv<10>(): ((tmp_9_fu_568_p3.read()[0].to_bool())? tmp_3_fu_638_p4.read(): tmp_2_fu_629_p4.read());
}

void exp_generic_decimal16_s::thread_tmp_V_fu_161_p4() {
    tmp_V_fu_161_p4 = p_Val2_s_fu_149_p1.read().range(14, 10);
}

void exp_generic_decimal16_s::thread_tmp_fu_757_p2() {
    tmp_fu_757_p2 = (or_ln849_2_fu_751_p2.read() & xor_ln214_fu_679_p2.read());
}

void exp_generic_decimal16_s::thread_trunc_ln1310_fu_299_p1() {
    trunc_ln1310_fu_299_p1 = shl_ln1253_fu_293_p2.read().range(19-1, 0);
}

void exp_generic_decimal16_s::thread_trunc_ln168_fu_655_p1() {
    trunc_ln168_fu_655_p1 = r_exp_V_2_fu_580_p3.read().range(5-1, 0);
}

void exp_generic_decimal16_s::thread_trunc_ln805_fu_416_p1() {
    trunc_ln805_fu_416_p1 = grp_fu_777_p3.read().range(12-1, 0);
}

void exp_generic_decimal16_s::thread_x_is_pinf_fu_539_p2() {
    x_is_pinf_fu_539_p2 = (and_ln18_reg_818_pp0_iter9_reg.read() & xor_ln936_fu_534_p2.read());
}

void exp_generic_decimal16_s::thread_xor_ln214_fu_679_p2() {
    xor_ln214_fu_679_p2 = (or_ln214_1_fu_556_p2.read() ^ ap_const_lv1_1);
}

void exp_generic_decimal16_s::thread_xor_ln338_1_fu_729_p2() {
    xor_ln338_1_fu_729_p2 = (or_ln338_fu_603_p2.read() ^ ap_const_lv1_1);
}

void exp_generic_decimal16_s::thread_xor_ln338_fu_690_p2() {
    xor_ln338_fu_690_p2 = (icmp_ln338_reg_870_pp0_iter9_reg.read() ^ ap_const_lv1_1);
}

void exp_generic_decimal16_s::thread_xor_ln849_fu_745_p2() {
    xor_ln849_fu_745_p2 = (or_ln849_1_fu_740_p2.read() ^ ap_const_lv1_1);
}

void exp_generic_decimal16_s::thread_xor_ln936_fu_534_p2() {
    xor_ln936_fu_534_p2 = (p_Result_12_reg_806_pp0_iter9_reg.read() ^ ap_const_lv1_1);
}

void exp_generic_decimal16_s::thread_zext_ln498_fu_495_p1() {
    zext_ln498_fu_495_p1 = esl_zext<64,9>(m_diff_hi_V_fu_481_p4.read());
}

void exp_generic_decimal16_s::thread_zext_ln659_fu_205_p1() {
    zext_ln659_fu_205_p1 = esl_zext<6,5>(tmp_V_fu_161_p4.read());
}

void exp_generic_decimal16_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

